apiVersion: v1
kind: Service

metadata:
  name: devopsrag-service
  namespace: devopsrag

spec:
  type: NodePort

  selector:
    app: devopsrag-api

  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30080
